/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author raze2
 */
import java.awt.Color;
import javax.swing.JOptionPane;
public class jfrmguia3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmguia3.class.getName());

    /**
     * Creates new form jfrmguia3
     */
    public jfrmguia3() {
        initComponents();
        this.setTitle("Motherboard");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(500,450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jlblNomPiezas = new javax.swing.JLabel();
        jlbldescripcion = new javax.swing.JLabel();
        jlblPiezas = new javax.swing.JLabel();
        jlblUtilidad = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jlblNomPiezas.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jlblNomPiezas.setText("Nombre del Componente");

        jlbldescripcion.setText("Concepto");

        jlblUtilidad.setText("Función Principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jlblNomPiezas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jlbldescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jlblPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jlblUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblNomPiezas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbldescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlblUtilidad)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItem3.setText("Abrir");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Guardar");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Componentes del PC");

        jMenuItem6.setText("MotherBoard");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Procesador");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Memoria RAM");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Disco Duro (HDD)");
        jMenuItem9.addActionListener(this::jMenuItem9ActionPerformed);
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Unidad SSD");
        jMenuItem10.addActionListener(this::jMenuItem10ActionPerformed);
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Fuente de Poder");
        jMenuItem11.addActionListener(this::jMenuItem11ActionPerformed);
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Tarjeta de Video (GPU)");
        jMenuItem12.addActionListener(this::jMenuItem12ActionPerformed);
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Tarjeta de Red");
        jMenuItem13.addActionListener(this::jMenuItem13ActionPerformed);
        jMenu2.add(jMenuItem13);

        jMenuItem14.setText("Cooler del Procesador");
        jMenuItem14.addActionListener(this::jMenuItem14ActionPerformed);
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Ventilador del gabinete");
        jMenuItem15.addActionListener(this::jMenuItem15ActionPerformed);
        jMenu2.add(jMenuItem15);

        jMenuItem16.setText("Tarjeta de Sonido");
        jMenuItem16.addActionListener(this::jMenuItem16ActionPerformed);
        jMenu2.add(jMenuItem16);

        jMenuItem17.setText("Batería CMOS");
        jMenuItem17.addActionListener(this::jMenuItem17ActionPerformed);
        jMenu2.add(jMenuItem17);

        jMenuItem18.setText("Cable SATA");
        jMenuItem18.addActionListener(this::jMenuItem18ActionPerformed);
        jMenu2.add(jMenuItem18);

        jMenuItem19.setText("Cable de alimetación");
        jMenuItem19.addActionListener(this::jMenuItem19ActionPerformed);
        jMenu2.add(jMenuItem19);

        jMenuItem20.setText("BIOS/UEFI");
        jMenuItem20.addActionListener(this::jMenuItem20ActionPerformed);
        jMenu2.add(jMenuItem20);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem21.setText("Acerca del Programa");
        jMenuItem21.addActionListener(this::jMenuItem21ActionPerformed);
        jMenu3.add(jMenuItem21);

        jMenuItem22.setText("Créditos");
        jMenuItem22.addActionListener(this::jMenuItem22ActionPerformed);
        jMenu3.add(jMenuItem22);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
jlblNomPiezas.setText("Fuente de Poder");
jlblNomPiezas.setForeground(Color.white);
jlbldescripcion.setText("Componente que transforma la corriente alterna del tomacorriente en corriente directa.");
jlbldescripcion.setForeground(Color.white);
jlblUtilidad.setText("Proveer la energía eléctrica adecuada y regulada a todos los componentes internos del PC.");
jlblUtilidad.setForeground(Color.white);
jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foldimagenes/fuente.png")));
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "Desarrollado por: Luis David de la Cruz Natareno\nCuarto Bachillerato\nSección: D\nClave: 6", "Créditos", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
jlblNomPiezas.setText("Motherboard");
jlblNomPiezas.setForeground(Color.white);
jlbldescripcion.setText("Circuito impreso principal que conecta todos los componentes de la computadora.");
jlbldescripcion.setForeground(Color.white);
jlblUtilidad.setText("Coordinar, comunicar y distribuir energía eléctrica a todos los demás dispositivos.");
jlblUtilidad.setForeground(Color.white);
jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foldimagenes/motherboard.png")));
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Funcionalidad Abrir");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Funcionalidad Guardar");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
jlblNomPiezas.setText("Procesador (CPU)");
jlblNomPiezas.setForeground(Color.white);
jlbldescripcion.setText("El cerebro del ordenador encargado de realizar las operaciones lógicas y matemáticas.");
jlbldescripcion.setForeground(Color.white);
jlblUtilidad.setText("Interpretar instrucciones de programas y procesar los datos de las aplicaciones.");
jlblUtilidad.setForeground(Color.white);
jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foldimagenes/cpu.png")));
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
jlblNomPiezas.setText("Memoria RAM");
jlblNomPiezas.setForeground(Color.white);
jlbldescripcion.setText("Memoria de acceso aleatorio de alta velocidad y almacenamiento de datos volátil.");
jlbldescripcion.setForeground(Color.white);
jlblUtilidad.setText("Almacenar temporalmente los datos de los programas que el CPU está ejecutando en tiempo real.");
jlblUtilidad.setForeground(Color.white);
jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foldimagenes/ram.png")));
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "Sistema de Información de Hardware-Luis David de la Cruz", "Acerca del programa", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
jlblNomPiezas.setText("Disco Duro (HDD)");
jlblNomPiezas.setForeground(Color.white);
jlbldescripcion.setText("Dispositivo magnético de almacenamiento masivo no volátil.");
jlbldescripcion.setForeground(Color.white);
jlblUtilidad.setText("Guardar de forma permanente archivos grandes, sistemas operativos y programas del usuario.");
jlblUtilidad.setForeground(Color.white);
jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foldimagenes/Laptop-hard-drive-exposed_remix_transparent (1).png")));
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
jlblNomPiezas.setText("Unidad SSD");
jlblNomPiezas.setForeground(Color.white);
jlbldescripcion.setText("Dispositivo de almacenamiento de estado sólido basado en memorias flash.");
jlbldescripcion.setForeground(Color.white);
jlblUtilidad.setText("Ofrecer velocidades de lectura y escritura ultrarrápidas para iniciar el sistema operativo al instante.");
jlblUtilidad.setForeground(Color.white);
jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foldimagenes/SSD.png")));
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
jlblNomPiezas.setText("Tarjeta de Video (GPU)");
jlblNomPiezas.setForeground(Color.white);
jlbldescripcion.setText("Tarjeta de expansión especializada en el procesamiento de datos gráficos y de video.");
jlbldescripcion.setForeground(Color.white);
jlblUtilidad.setText("Renderizar imágenes, juegos y animaciones 3D para mostrarlas fluidamente en el monitor.");
jlblUtilidad.setForeground(Color.white);
jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foldimagenes/tarjetavideo.png")));
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
jlblNomPiezas.setText("Tarjeta de Red");
jlblNomPiezas.setForeground(Color.white);
jlbldescripcion.setText("Hardware de red (Ethernet o Wi-Fi) encargado de la comunicación del ordenador.");
jlbldescripcion.setForeground(Color.white);
jlblUtilidad.setText("Permitir que la computadora se conecte a redes locales y navegue en Internet.");
jlblUtilidad.setForeground(Color.white);
jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foldimagenes/tarjetared.png")));
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
jlblNomPiezas.setText("Cooler del Procesador");
jlblNomPiezas.setForeground(Color.white);
jlbldescripcion.setText("Sistema de enfriamiento (por aire o líquido) montado directamente sobre el CPU.");
jlbldescripcion.setForeground(Color.white);
jlblUtilidad.setText("Disipar el calor extremo generado por el procesador para evitar daños por sobrecalentamiento.");
jlblUtilidad.setForeground(Color.white);
jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foldimagenes/cooler.png")));
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
jlblNomPiezas.setText("Ventilador del Gabinete");
jlblNomPiezas.setForeground(Color.white);
jlbldescripcion.setText("Extractor o ventilador interno acoplado al chasis de la computadora.");
jlbldescripcion.setForeground(Color.white);
jlblUtilidad.setText("Generar un flujo de aire constante para expulsar el calor acumulado dentro del gabinete.");
jlblUtilidad.setForeground(Color.white);
jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foldimagenes/ventiladorgab.png")));
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
jlblNomPiezas.setText("Tarjeta de Sonido");
jlblNomPiezas.setForeground(Color.white);
jlbldescripcion.setText("Dispositivo de expansión encargado de digitalizar y procesar señales de audio.");
jlbldescripcion.setForeground(Color.white);
jlblUtilidad.setText("Permitir la entrada y salida de audio de alta fidelidad hacia bocinas, audífonos y micrófonos.");
jlblUtilidad.setForeground(Color.white);
jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foldimagenes/soundcard.png")));
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
jlblNomPiezas.setText("Batería CMOS");
jlblNomPiezas.setForeground(Color.white);
jlbldescripcion.setText("Pequeña pila de botón (generalmente CR2032) ubicada en la tarjeta madre.");
jlbldescripcion.setForeground(Color.white);
jlblUtilidad.setText("Mantener energizada la memoria CMOS para guardar la hora del sistema y configuraciones del BIOS.");
jlblUtilidad.setForeground(Color.white);
jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foldimagenes/cmos.png")));
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
jlblNomPiezas.setText("Cable SATA");
jlblNomPiezas.setForeground(Color.white);
jlbldescripcion.setText("Interfaz de transferencia de datos en serie entre la placa base y discos.");
jlbldescripcion.setForeground(Color.white);
jlblUtilidad.setText("Conectar discos duros, unidades SSD y lectoras de discos a la Motherboard para transmitir datos.");
jlblUtilidad.setForeground(Color.white);
jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foldimagenes/satacable.png")));
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
jlblNomPiezas.setText("Cable de Alimentación");
jlblNomPiezas.setForeground(Color.white);
jlbldescripcion.setText("Cable eléctrico conductor externo que se conecta a la toma de corriente.");
jlbldescripcion.setForeground(Color.white);
jlblUtilidad.setText("Vincular la red eléctrica externa del hogar con la entrada de la Fuente de Poder del PC.");
jlblUtilidad.setForeground(Color.white);
jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foldimagenes/cablea.png")));
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
jlblNomPiezas.setText("BIOS / UEFI");
jlblNomPiezas.setForeground(Color.white);
jlbldescripcion.setText("Firmware fundamental guardado en un chip integrado en la tarjeta madre.");
jlbldescripcion.setForeground(Color.white);
jlblUtilidad.setText("Inicializar, verificar el hardware en el arranque y cargar el sistema operativo de la máquina.");
jlblUtilidad.setForeground(Color.white);
jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foldimagenes/biosi.png")));
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmguia3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblNomPiezas;
    private javax.swing.JLabel jlblPiezas;
    private javax.swing.JLabel jlblUtilidad;
    private javax.swing.JLabel jlbldescripcion;
    // End of variables declaration//GEN-END:variables
}
